app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    secure_password = db.Column(db.String(255), nullable=False)
    profile_pic_path = db.Column(db.String())
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.secure_password, password)

    def save_u(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


class Admin (UserMixin, db.Model):
    __tablename__ = 'admin'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    secure_password = db.Column(db.String(255), nullable=False)
    profile_pic_path = db.Column(db.String())
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.secure_password, password)

    def save_a(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref='role', lazy="dynamic")
    admin = db.relationship('Admin', backref='role', lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write a brief bio about you.',
                        validators=[Required()])
    submit = SubmitField('Save')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

mail = Mail()

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])

     # configure UploadSet
    configure_uploads(app,photos)


    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,forms,error

app/main/views.py
# from os import name
# from flask import render_template, redirect, url_for, abort, request
# from . import main
# from flask_login import login_required, current_user
# from ..models import User, Admin, Role
# from .. import db, photos
# from .forms import UpdateProfile


# @main.route('/')
# def index():
#   return render_template('index.html')


# @main.route('/user/<name>')
# def profile(name):
#     user = User.query.filter_by(username=name).first()

#     if user is None:
#         abort(404)

#     return render_template("profile/profile.html", user=user)


# @main.route('/user/<name>/profileupdate', methods=['GET', 'POST'])
# @login_required
# def profileupdate(name):
#     user = User.query.filter_by(username=name).first()
#     form = UpdateProfile()
#     if user == None:
#         abort(404)

#     if form.validate_on_submit():
#         user.bio = form.bio.data

#         db.session.add(user)
#         db.session.commit()

#         return redirect(url_for('.profile', name=user.username))

#     return render_template('profile/update.html', form=form, user=user)


# @main.route('/user/<name>/update pic', methods=['POST'])
# @login_required
# def update_pic(name):
#     user = User.query.filter_by(username=name).first()
#     if 'photo' in request.files:
#         filename = photos.save(request.files['photo'])
#         path = f'photos/{filename}'
#         user.profile_pic_path = path
#         db.session.commit()
#     return redirect(url_for('main.profile', name=name))

from os import name
from flask import render_template, redirect, url_for, abort, request
from . import main
from flask_login import login_required, current_user
from ..models import User, Admin, Role
from .. import db, photos
from .forms import UpdateProfile


@main.route('/')
# @login_required
def index():
  return render_template('index.html')

@main.route('/product')
# @login_required
def product():
  return render_template('product.html')



# @main.route('/user/<name>/homepage', methods=['GET', 'POST'])
# def index():
#   return render_template('home.html')


@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username=name).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/user/<name>/profileupdate', methods=['GET', 'POST'])
@login_required
def profileupdate(name):
    user = User.query.filter_by(username=name).first()
    form = UpdateProfile()
    if user == None:
        abort(404)

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', name=user.username))

    return render_template('profile/update.html', form=form, user=user)


@main.route('/user/<name>/update pic', methods=['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username=name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', name=name))

app/templates/account.html
{% extends "index.html" %}
{% block content %}

   <div class="content-section">
      <div class="media">
         <img class="rounded-circle account-img" src=" {{ image_file }}" alt="Profile-pic">
         <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary"> {{ current_user.email}}</p>
         </div>
      </div>
     
         <form action="" method="POST" enctype="multipart/form-data">
             {{form.hidden_tag() }}
             <fieldset class="form-group">
                 <legend class="border-bottom mb-4"> Account Info</legend>
                 <div class="form-group">
                     {{form.username.label(class="form-control-label")}}
                     {%if form.username.errors%}
                     {{form.username(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.username.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.username(class="form-control form-control-lg ")}}
                     {% endif %}
                 </div>
 
                 <div class="form-group">
                     {{form.email.label(class="form-control-label")}}
                     {%if form.email.errors%}
                     {{form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.email(class="form-control form-control-lg ")}}
                     {% endif %}
                  </div>
                  <div class="form-group">
                     {{form.picture.label()}}
                     {{form.picture(class="form-control-file")}}
                     {% if form.picture.errors %}
                     {% for error in form.picture.errors %}
                         <span class="text-danger">{{ error }}</span><br>
                         {% endfor %}

                     {% endif%}
                  
                  
                  </div>
                 <div class="form-group">
                     {{form.submit(class="btn btn-outline-info")}}
 
                 </div>
             </fieldset>
 
         </form>
  
   </div>
   
{% endblock content %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<style>
    #background {
        background-image: url('../static/nadine-redlich-SEF34uHb1jE-unsplash.jpg');
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
    }
</style>

<div class="container" id="background">
    <h1 style="font-size: 40px; text-align: center; font-weight: bold;">OUR CONTACTS</h1>
    <p style="text-align: center; font-size: 25px;">Down below find various ways to contact us</p>

    <div class="row">
        <div class="col-md-6">
            <p style="font-size: 25px; font-weight: bold;"><span>ADDRESS<br></span> State House Road P.O Box: 40530-00100 Nairobi, Kenya.
            </p>

            <div class="col-md-6">
                <p style="font-size: 25px; font-weight: bold; color: white;"><span>PHONE NUMBERS<br></span> <a href="" style="font-weight: bold;">+254 726 015886,  +254 715 000110, +254 718 818642, +254 705
                        952719</a></p>
            </div>

            <div class="col-md-6">

                <p style="font-size: 30px; font-weight: bold; color: white;"><span>EMAIL<br></span> <a href="">chebichiiserem@gmail.com</a></p>
            </div>

            <div class="col-md-6">

                <p style="font-size: 30px; font-weight: bold; color: white;"><span>WEBSITE<br></span> <a href="#">https://github.com/Chebichii-Lab</a></p>

            </div>

            <div class="row">
                <div class="col-lg-12">
                    <form action="#" class="bg-white  contact-form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Email">
                        </div>
                        <div class="form-group">
                            <textarea name="" id="" class="form-control" placeholder="Message"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary btn-md">
                        </div>
                    </form>

                </div>
            </div>

            <footer>
                <p class="copyright text-muted" style="text-align: center;">Copyright &copy; Natasha Serem, Melby Okozi,
                    Faith Chepngetich and Dennis Kiplangat Cheruiyot. 2021.</p>
             </footer>
</div>
</div>
</div>

</html>

app/templates/form.html
 

<h1>DELIVERY FORM<h1>
<form action="" method="post">
       <fieldset>
           <label for="username">Username</label>
           <input type="text" name="username" placeholder="username">
       </fieldset>
       <fieldset>
           <label for="email"> Email</label>
           <input type="email" name="email" placeholder="xyz@gmail.com">
       </fieldset>
       <fieldset>
           <label for="place">Place</label>
           <input type="place" name="place" placeholder="place">
       </fieldset>
       <button type="submit">Deliver</button>
   </form>

app/templates/home.html
<!-- {% extends 'bootstrap/base.html'%}
{% block content%}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="./photos/onions.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="./photos/peeper.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="./photos/varun-gaba-jmsf0DA1RU0-unsplash.jpg" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="./photos/cabbages.jpg" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="./photos/hoho.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock %} -->

app/templates/index.html
{% extends 'base.html'%}
{% block content%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container content-section">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/peeper.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">PEEPERS</h5>
                        <p class="card-text">Price: $6.89/kg</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/hoho.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">BELL PEPPERS</h5>
                        <p class="card-text">Price: $3.70/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/dan.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">DANIA</h5>
                        <p class="card-text">Price: $4.59/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/kitunguu.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">ONIONS</h5>
                        <p class="card-text">Price: $2.99/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/ve.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">EGG PLANT</h5>
                        <p class="card-text">Price: $2.99/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/varun-gaba-jmsf0DA1RU0-unsplash.jpg"
                        alt="Card image cap" width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title">POTATOES</h5>
                        <p class="card-text">Price: $5.99/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/carrots.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">VEGES</h5>
                        <p class="card-text">Price: $6.99/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="../static/photos/sweetberry.jpg" alt="Card image cap" width="200px"
                        height="200px">
                    <div class="card-body">
                        <h5 class="card-title">PEPPERS</h5>
                        <p class="card-text">Price: $4.99/kg.</p>
                        <a href="{{url_for('main.product')}}" class="btn btn-primary">Order</a>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>

</html>
{% endblock %}

app/templates/login.html
{% extends "index.html" %}
{% block content %}

   <div class="content-section">
      <div class="media">
         <img class="rounded-circle account-img" src=" {{ image_file }}" alt="Profile-pic">
         <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary"> {{ current_user.email}}</p>
         </div>
      </div>
     
         <form action="" method="POST" enctype="multipart/form-data">
             {{form.hidden_tag() }}
             <fieldset class="form-group">
                 <legend class="border-bottom mb-4"> Account Info</legend>
                 <div class="form-group">
                     {{form.username.label(class="form-control-label")}}
                     {%if form.username.errors%}
                     {{form.username(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.username.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.username(class="form-control form-control-lg ")}}
                     {% endif %}
                 </div>
 
                 <div class="form-group">
                     {{form.email.label(class="form-control-label")}}
                     {%if form.email.errors%}
                     {{form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.email(class="form-control form-control-lg ")}}
                     {% endif %}
                  </div>
                  <div class="form-group">
                     {{form.picture.label()}}
                     {{form.picture(class="form-control-file")}}
                     {% if form.picture.errors %}
                     {% for error in form.picture.errors %}
                         <span class="text-danger">{{ error }}</span><br>
                         {% endfor %}

                     {% endif%}
                  
                  
                  </div>
                 <div class="form-group">
                     {{form.submit(class="btn btn-outline-info")}}
 
                 </div>
             </fieldset>
 
         </form>
  
   </div>
   
{% endblock content %}

app/templates/navbar.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
</head>

<body>
    <div class="navbar navbar-inverse navbar-dark"  role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size:35px" href="/"> Online Grocery </a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.product')}}">Order here</a></li>
                <li><a href="{{url_for('main.index')}}">Contact Us</a></li>
                <br>
                <li style="color:rgb(255, 251, 255);padding:15px;font-weight: bolder;">{{current_user.username}}</li>
                <li><a href="{{url_for('main.profile',name=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                

                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>
    </div>
</body>

</html>

app/templates/order.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h1>Welcome to online Grocery proceed to order</h1>

        <div class="row">
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="https://images.unsplash.com/photo-1502234665511-5745ea0a6a29?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTB8fHRvbWF0b2VzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"
                        class="card-img-top" width="70px" alt="Onions">
                    <div class="card-body">
                        <h5 class="card-title">Tomatoes</h5>
                        <a href="#" class="btn btn-primary">Add to cart</a>
                        <p class="ml-2">ksh 100</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="https://images.unsplash.com/photo-1598278242809-6c21ee17aef1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8c3BpbmFjaHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
                        class="card-img-top" width="70px" alt="Onions">
                    <div class="card-body">
                        <h5 class="card-title">Spinach</h5>
                        <a href="#" class="btn btn-primary">Add to cart</a>
                        <p class="ml-2">ksh 100</p>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="https://images.unsplash.com/photo-1502234665511-5745ea0a6a29?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTB8fHRvbWF0b2VzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"
                        class="card-img-top" width="70px" alt="Onions">
                    <div class="card-body">
                        <h5 class="card-title">Carrots</h5>
                        <a href="{{url_for('.order')}}" class="btn btn-primary">Add to cart</a>
                        <span>
                            <p class="ml-6">ksh 100</p>
                        </span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
    </div>
    {% if user == current_user %}
    <a href="{{url_for('main.profileupdate',name=user.username)}}">Edit profile</a>

    {% endif %}
</div>
<div>
    {% if user == current_user %}
    <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">

        <input type="file" name="photo" class="form-control" required>
        <input type="submit">
    </form>

</div>
{% endif %}


{% endblock %}

app/templates/profile/profile_update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/register.html
{% extends "index.html" %}
{% block content %}

   <div class="content-section">
      <div class="media">
         <img class="rounded-circle account-img" src=" {{ image_file }}" alt="Profile-pic">
         <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary"> {{ current_user.email}}</p>
         </div>
      </div>
     
         <form action="" method="POST" enctype="multipart/form-data">
             {{form.hidden_tag() }}
             <fieldset class="form-group">
                 <legend class="border-bottom mb-4"> Account Info</legend>
                 <div class="form-group">
                     {{form.username.label(class="form-control-label")}}
                     {%if form.username.errors%}
                     {{form.username(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.username.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.username(class="form-control form-control-lg ")}}
                     {% endif %}
                 </div>
 
                 <div class="form-group">
                     {{form.email.label(class="form-control-label")}}
                     {%if form.email.errors%}
                     {{form.email(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {% for error in form.email.errors %}
                         <span>{{ error }}</span>
                         {% endfor %}
 
                     </div>
                     {% else %}
                      {{form.email(class="form-control form-control-lg ")}}
                     {% endif %}
                  </div>
                  <div class="form-group">
                     {{form.picture.label()}}
                     {{form.picture(class="form-control-file")}}
                     {% if form.picture.errors %}
                     {% for error in form.picture.errors %}
                         <span class="text-danger">{{ error }}</span><br>
                         {% endfor %}

                     {% endif%}
                  
                  
                  </div>
                 <div class="form-group">
                     {{form.submit(class="btn btn-outline-info")}}
 
                 </div>
             </fieldset>
 
         </form>
  
   </div>
   
{% endblock content %}